//! Data types for the TXT-to-XML converter.

use super::helpers::Fields;

/// Accumulated DI (Declaracao de Importacao) with its adi children.
pub(super) struct DiEntry {
    pub(super) fields: Fields,
    pub(super) adi_list: Vec<Fields>,
}

/// Accumulated data for a single det item.
pub(super) struct ItemBuild {
    pub(super) n_item: usize,
    pub(super) prod: Fields,
    pub(super) inf_ad_prod: String,
    pub(super) cest: Option<Fields>,
    pub(super) g_cred: Option<Fields>,
    pub(super) nve_list: Vec<String>,
    pub(super) di_list: Vec<DiEntry>,
    pub(super) det_export_list: Vec<Fields>,
    pub(super) rastro_list: Vec<Fields>,
    pub(super) veic_prod: Option<Fields>,
    pub(super) med: Option<Fields>,
    pub(super) arma_list: Vec<Fields>,
    pub(super) comb: Option<Fields>,
    pub(super) comb_cide: Option<Fields>,
    pub(super) encerrante: Option<Fields>,
    pub(super) recopi: Option<String>,
    pub(super) v_tot_trib: String,
    pub(super) icms_tag: String,
    pub(super) icms_data: Option<Fields>,
    pub(super) icms_ufdest: Option<Fields>,
    pub(super) ipi_header: Option<Fields>,
    pub(super) ipi_cst: String,
    pub(super) ipi_v_ipi: String,
    pub(super) ipi_v_bc: String,
    pub(super) ipi_p_ipi: String,
    pub(super) ipi_q_unid: String,
    pub(super) ipi_v_unid: String,
    pub(super) ii: Option<Fields>,
    pub(super) pis_cst: String,
    pub(super) pis_v_bc: String,
    pub(super) pis_p_pis: String,
    pub(super) pis_v_pis: String,
    pub(super) pis_q_bc_prod: String,
    pub(super) pis_v_aliq_prod: String,
    pub(super) pis_st: Option<Fields>,
    pub(super) pis_st_v_bc: String,
    pub(super) pis_st_p_pis: String,
    pub(super) pis_st_q_bc_prod: String,
    pub(super) pis_st_v_aliq_prod: String,
    pub(super) pis_st_v_pis: String,
    pub(super) cofins_cst: String,
    pub(super) cofins_v_bc: String,
    pub(super) cofins_p_cofins: String,
    pub(super) cofins_v_cofins: String,
    pub(super) cofins_q_bc_prod: String,
    pub(super) cofins_v_aliq_prod: String,
    pub(super) cofins_st: Option<Fields>,
    pub(super) cofins_st_v_bc: String,
    pub(super) cofins_st_p_cofins: String,
    pub(super) cofins_st_q_bc_prod: String,
    pub(super) cofins_st_v_aliq_prod: String,
    pub(super) cofins_st_v_cofins: String,
    pub(super) issqn: Option<Fields>,
    pub(super) imposto_devol: Option<Fields>,
}
